---
abstract: "SHARYANTO's patch modules"
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.001, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-SHARYANTO-Patches
requires:
  HTTP::Daemon::Patch::IPv6: 0
  HTTP::Headers::Patch::DontUseStorable: 0
  HTTP::Tiny::Patch::LogAny: 0
  LWP::UserAgent::Patch::HTTPSHardTimeout: 0
  LWP::UserAgent::Patch::LogRequestContent: 0
  LWP::UserAgent::Patch::LogResponse: 0
  LWP::UserAgent::Patch::Retry: 0
  Log::Any::Adapter::Core::Patch::SetDumperIndent: 0
  Log::Any::Adapter::Core::Patch::UseDataDump: 0
  Log::Any::Adapter::Core::Patch::UseDataDumperPerltidy: 0
  Net::HTTP::Methods::Patch::LogRequest: 0
  Time::Duration::Patch::Millisecond: 0
  UUID::Random::Patch::UseMRS: 0
resources: {}
version: 0.06
